# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba48792ffece12342c903279afbffa09a1e18ac88d925b764f82af4f0493548a704bc0512d20a3b70204b4e5bb8ebce656066b17677bb55fd07685bccbdcd1ce

test:
  secret_key_base: 2c9bb92c9f6f951b8d5dea0d526e04d71a1c2e527d9a1511415d21088173aa853fe9ed510ec13fc31fe08c1d1fbb4f8c1e17a65c76ea1f5825f282df8da10539

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
